const assert = require('assert');
const fs = require('fs');

const html = fs.readFileSync('index.html', 'utf8');

assert.match(html, /const API_TIMEOUT_MS = 45000;/);
assert.match(html, /async function apiFetch\(url, options\)/);
assert.match(html, /const data = await apiPost\(\{action:"loginSecure", name, empId, date:todayLocal\(\)\}\);/);
assert.doesNotMatch(html, /apiRequest\(\{action:"login", name, empId\}\)/);
assert.doesNotMatch(html, /\n\s*checkServer\(\);\s*\n/);
assert.match(html, /if\(operationRequestInFlight\)return;/);
assert.match(html, /loadMySchedule\(true\)/);
assert.match(html, /최근 저장정보입니다\. 서버에서 현재 사번·노선·배차를 확인 중/);
assert.match(html, /function tripGapSummary\(trip\)/);
assert.match(html, /function tripOperationalState\(data,trip,index\)/);
assert.match(html, /function renderDriverLiveDashboard\(root,data\)/);
assert.match(html, /id="driverWorkMenu"/);
assert.match(html, /data-driver-menu="ALERT"/);
assert.match(html, /data-driver-menu="LOG"/);
assert.match(html, /data-driver-menu="REPORT"/);
assert.match(html, /data-driver-menu="EMERGENCY"/);
assert.match(html, /class="driver-emergency-actions"/);
assert.match(html, /href="tel:112"/);
assert.match(html, /href="tel:119"/);
assert.match(html, /driver-live-dashboard/);
assert.match(html, /driverLiveLocationToggle/);
assert.match(html, /완료/);
assert.match(html, /운행 중/);
assert.match(html, /출발 대기/);
assert.match(html, /예정/);
assert.match(html, /앞차 배차간격/);
assert.match(html, /뒷차 배차간격/);
assert.match(html, /전체 펼침/);
assert.match(html, /탕별 카드/);
assert.match(html, /trip\.completed/);
assert.match(html, /실시간 위치 자동 기록 시작/);
assert.match(html, /navigator\.geolocation\.watchPosition/);
assert.match(html, /automaticRunEvent\(trip,"TURN",position\)/);
assert.match(html, /source:"GPS_AUTO"/);
assert.match(html, /plannedTurn:trip\.turnTime/);
assert.match(html, /id="managerRoute"/);
assert.match(html, /value="ALL">전체 노선 현황/);
assert.match(html, /managerDispatchBootstrap",token:authToken,date,route/);
assert.match(html, /route:document\.getElementById\("managerRoute"\)\.value/);
assert.match(html, /function applyRouteBrand\(route, role = currentRole\)/);
assert.match(html, /기사 노선·사번 이력 보기/);
assert.match(html, /전체 정류장/);
assert.match(html, /data\.routeProfile\?\.stops/);
assert.match(html, /과거 실제기록/);
assert.match(html, /예정 스케줄/);
assert.match(html, /recordable=!temporalState\|\|temporalState==="CURRENT"/);
assert.match(html, /당시 사원번호/);
assert.match(html, /for\(let i=1;i<=27;i\+\+\)seq\.add/);
assert.match(html, /function populateIncidentSequenceRange\(\)/);
assert.doesNotMatch(html, /fillText\("소신여객 70번 배차 현황/);

console.log('Frontend resilience tests passed');
